### ISSUE TITLE
Installation fails with django 1.6 

### ISSUE THREAD

**Issue by asmaier** [diefenbach/lfs-buildout-development#4]
The installation process fails with the following error 

```
$ bin/django syncdb
Traceback (most recent call last):
File "bin/django", line 37, in <module>
sys.exit(djangorecipe.manage.main('lfs_project.settings'))
File "./lfs-installer/eggs/djangorecipe-1.1.2-py2.7.egg/djangorecipe/manage.py", line 19, in main
management.execute_manager(mod)
AttributeError: 'module' object has no attribute 'execute_manager'
```

The reason seems to be that the execute_manager method is not available anymore in django 1.6, see also http://stackoverflow.com/questions/18048232/satchmo-clonesatchmo-py-importerror-cannot-import-name-execute-manager

**Comment by pigletto** [comment]
Current LFS version works with django 1.4, there is no support yet for 1.5 +

**Comment by asmaier** [comment]
It would be nice if the documentation could be updated to state explicitly that only django 1.4 is supported, because in the documentation at http://docs.getlfs.com/en/latest/introduction/installation.html I cannot find any information, which version of django is required by lfs.
